### ISSUE TITLE
extract data from csv data

### ISSUE THREAD

**Issue by elkasimi** [rewayat/rewayat-db#2]
See If we can extract data from:
https://github.com/ceefour/hadith-islamware

**Comment by acbeni** [comment]
for the splitting issue i tried the code
```java
Arrays.stream(text.split("\\|")).forEach(System.out::println);
```
and it works totally fine

Also i came across this website which would allow you to check the unicode of a charachter http://unicode.scarfboy.com

However i don't get what the numbers mean at the hadith start |1|7 ....? 😅

**Comment by acbeni** [comment]
ok i feel stupid :disappointed: actually just use https://github.com/osiegmar/FastCSV or any csv parsing library and specify `|` as a separator

**Comment by elkasimi** [comment]
Thanks a lot!
In fact I found the same. But still feel it is weird that Comma Separated Values (CSV) can be Pipe Separated Values :)
